In [1]:
import pandas as pd
import numpy as np

In [107]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [108]:
path = "/content/drive/MyDrive/Colab Notebooks/IIT Kharagpur/"
df = pd.read_csv(path + "1mg_data_annotators_copy - sarthak_hindi (1).csv")

In [109]:
df = df[['Label', 'manually_translated_hindi']]
#df = df.join(pd.get_dummies(df.Label))
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
df['Label'] = oe.fit_transform(np.array(df['Label']).reshape(-1, 1))
#df.drop(["Label"], axis=1, inplace = True)
df

Label                          manually_translated_hindi    L
0        Other  क्या सांसों की बदबू का कीटोन्स से कोई लेना-देन...  2.0
1      Disease         क्या एच पाइलोरी आईटीपी का कारण बन सकता है?  0.0
2      Disease  क्या होता है यदि एक वसामय पुटी से सभी थैली को ...  0.0
3         Drug                                 एंटीमैटिक क्या है?  1.0
4      Disease  क्या टॉन्सिल स्टोन आपके दांतों को नुकसान पहुंच...  0.0
..         ...                                                ...  ...
232  Treatment                                 एडेनोपैथी क्या है?  3.0
233  Treatment                क्या आयरन सप्लीमेंट से गैस बनती है?  3.0
234  Treatment   पोसेलेन के डेन्चर के लिए सबसे अच्छा रंग क्या है?  3.0
235  Treatment  कल कोलोनोस्कोपी लेकिन मेरे मासिक धर्म चक्र शुर...  3.0
236  Treatment  क्या एक ट्यूबल बंधाव के साथ एक महिला अभी भी ओव...  3.0

[237 rows x 3 columns]

In [110]:
'''path = 'google/muril-base-cased'
## Loading the model
from transformers import AutoModel, AutoTokenizer
import torch
tokenizer = AutoTokenizer.from_pretrained(path)
model = AutoModel.from_pretrained(path,output_hidden_states=True)
## Embeddings 
text ="कोई अच्छी सी फिल्म लगायो"
print(tokenizer.convert_ids_to_tokens(tokenizer.encode(text)))
input_encoded = tokenizer.encode_plus(text, return_tensors="pt")
with torch.no_grad():
         states = model(**input_encoded).hidden_states
output = torch.stack([states[i] for i in range(len(states))])
output = output.squeeze()
print("Output shape is {}".format(output.shape))'''

'path = \'google/muril-base-cased\'\n## Loading the model\nfrom transformers import AutoModel, AutoTokenizer\nimport torch\ntokenizer = AutoTokenizer.from_pretrained(path)\nmodel = AutoModel.from_pretrained(path,output_hidden_states=True)\n## Embeddings \ntext ="कोई अच्छी सी फिल्म लगायो"\nprint(tokenizer.convert_ids_to_tokens(tokenizer.encode(text)))\ninput_encoded = tokenizer.encode_plus(text, return_tensors="pt")\nwith torch.no_grad():\n         states = model(**input_encoded).hidden_states\noutput = torch.stack([states[i] for i in range(len(states))])\noutput = output.squeeze()\nprint("Output shape is {}".format(output.shape))'

In [111]:
#!pip install pyspark

In [112]:
#!pip install sparknlp

In [113]:
#from sparknlp.base import *
#from sparknlp.annotator import *

In [114]:
#from pyspark import SparkContext
#sc = None#=SparkContext()

In [115]:
#import sparknlp

In [116]:
#spark = sparknlp.start()

In [117]:
#sent_embeddings = BertSentenceEmbeddings.pretrained("sent_bert_muril", "xx").setInputCols("sentence").setOutputCol("bert_sentence")

In [118]:
#sent_embeddings()

In [119]:
#nlp_pipeline = Pipeline(stages=[document_assembler, sentence_detector, sent_embeddings ])

In [120]:
%%capture
!pip install sentence-transformers

In [121]:
%%capture
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('distiluse-base-multilingual-cased-v2')#bert-base-nli-mean-tokens')

In [122]:
#%%capture
#!pip install transformers

In [123]:
#from transformers import AutoModel
#model = AutoModel.from_pretrained("ai4bharat/indic-bert")

In [124]:
sentences = df["manually_translated_hindi"]
len(sentences)

237

In [125]:
title_embeddings = sbert_model.encode(sentences)
#7 secs for 200 sentences
#16+ mins for 20k

In [126]:
df["embeddings"] = title_embeddings.tolist()

In [127]:
split_df = pd.DataFrame(df['embeddings'].tolist())

In [128]:
split_df

0         1         2         3         4         5         6    \
0   -0.025790 -0.031240  0.014151  0.011566 -0.050515  0.026118  0.002407   
1    0.004274 -0.002293  0.006431  0.007926 -0.030170 -0.005818 -0.009912   
2   -0.010823 -0.026562  0.000221 -0.011665 -0.040837 -0.046347 -0.001730   
3   -0.006867 -0.045847 -0.005699 -0.002603 -0.066110  0.030698 -0.001158   
4   -0.023855 -0.001197  0.013673  0.007836 -0.050959 -0.028017 -0.026709   
..        ...       ...       ...       ...       ...       ...       ...   
232  0.032966  0.012899 -0.022092  0.007133 -0.063142  0.012842 -0.045452   
233 -0.032911 -0.043971 -0.013824  0.005874 -0.066568  0.013346 -0.044526   
234  0.027872 -0.008575  0.010736  0.005021 -0.061363 -0.017652 -0.004742   
235  0.004278  0.044048  0.003260  0.012375 -0.020970  0.014618  0.029832   
236  0.005047  0.025038  0.000581  0.033386 -0.022295 -0.032023  0.043143   

          7         8         9    ...       502       503       504  \
0    0.016235  0.018502  0.063142  ... -0.002802  0.001530  0.044891   
1    0.015903 -0.030828  0.071091  ... -0.012784  0.013950  0.031070   
2   -0.006837  0.000342 -0.045054  ... -0.012916  0.028561  0.006174   
3   -0.024844 -0.060985 -0.111249  ... -0.025141  0.007667  0.027613   
4   -0.009765 -0.015251  0.075359  ... -0.030684 -0.034133 -0.008233   
..        ...       ...       ...  ...       ...       ...       ...   
232 -0.038490 -0.049112 -0.095431  ... -0.041279 -0.006466  0.009871   
233 -0.021544  0.001221  0.009597  ... -0.006276 -0.034514  0.064515   
234  0.067996  0.007561 -0.114259  ... -0.012169 -0.026700  0.011780   
235  0.063552 -0.044062  0.111024  ...  0.123476  0.004144  0.047869   
236 -0.000909 -0.062114  0.141554  ... -0.003030  0.002587  0.041508   

          505       506       507       508       509       510       511  
0   -0.040755  0.021247  0.019635  0.016689 -0.004487  0.001639  0.039686  
1   -0.016678  0.022872 -0.009490 -0.044757 -0.039170 -0.004373 -0.004814  
2   -0.011207 -0.010093  0.018822  0.000348  0.015430 -0.029235  0.001540  
3   -0.068182  0.008363 -0.004988  0.032274 -0.021151 -0.001550 -0.036625  
4   -0.011706  0.010247  0.046017 -0.059709 -0.006068  0.013821 -0.028077  
..        ...       ...       ...       ...       ...       ...       ...  
232 -0.036353 -0.021180  0.045069 -0.019030 -0.012118 -0.003931 -0.006557  
233 -0.046994  0.013840  0.035441 -0.030915 -0.029846 -0.016360  0.023673  
234 -0.012726 -0.053500  0.038418  0.009961  0.014944 -0.003744  0.013121  
235  0.018385  0.012857 -0.038240 -0.035166 -0.005938 -0.000794  0.011078  
236 -0.036957  0.010356  0.028458  0.024989 -0.006206 -0.003956 -0.050140  

[237 rows x 512 columns]

UMAP uses a predefined distance function as a similarity measure. It tries to preserve the distances between points in lower-dimensional space. This makes it perfect for SentenceBERT embedding as the model has a CosineLoss baked in.

In [129]:
'''%%capture
!pip install umap-learn '''

'%%capture\n!pip install umap-learn '

In [130]:
'''import umap
reducer = umap.UMAP()

umap_embedding = reducer.fit_transform(split_df)
umap_embedding.shape'''

'import umap\nreducer = umap.UMAP()\n\numap_embedding = reducer.fit_transform(split_df)\numap_embedding.shape'

In [131]:
from sklearn.decomposition import PCA

pca = PCA(n_components=32)
pca.fit(split_df)
split_df_32 = pca.transform(split_df)

In [132]:
split_df_32 = pd.DataFrame(split_df_32)

In [133]:
df = df.join(split_df_32)
df.drop(["manually_translated_hindi", "embeddings"], axis=1, inplace=True)

In [134]:
df

Label    L         0         1         2         3         4  \
0        Other  2.0  0.072486  0.000240 -0.004098 -0.126902 -0.021958   
1      Disease  0.0  0.119010 -0.030077 -0.078106  0.012318 -0.050165   
2      Disease  0.0 -0.070066  0.032851  0.037144 -0.087974 -0.106349   
3         Drug  1.0 -0.184985 -0.259077 -0.135021  0.120531  0.059713   
4      Disease  0.0  0.156783  0.042057 -0.097449 -0.094851 -0.209433   
..         ...  ...       ...       ...       ...       ...       ...   
232  Treatment  3.0 -0.267835 -0.258083  0.008070 -0.033937  0.112359   
233  Treatment  3.0 -0.048973 -0.027858 -0.016536 -0.138771 -0.042490   
234  Treatment  3.0 -0.225683 -0.042007  0.049681 -0.097173  0.032431   
235  Treatment  3.0  0.148338  0.193006  0.016603  0.096955  0.186935   
236  Treatment  3.0  0.249119  0.169346 -0.095952 -0.023222  0.193670   

            5         6         7  ...        22        23        24  \
0    0.064858  0.003803  0.063781  ...  0.016568 -0.110176 -0.002603   
1   -0.080790  0.074567 -0.000021  ... -0.052118  0.039016 -0.028220   
2    0.100469 -0.021147 -0.059109  ...  0.051461  0.010076  0.060595   
3   -0.062565  0.084242  0.213166  ...  0.022254 -0.041332  0.015025   
4    0.121015 -0.067493  0.153687  ...  0.073441  0.020415 -0.030133   
..        ...       ...       ...  ...       ...       ...       ...   
232 -0.090215  0.087896  0.138282  ... -0.073115 -0.045910  0.000180   
233 -0.054142  0.069973 -0.018406  ...  0.016914 -0.078891  0.093286   
234 -0.016417  0.000849 -0.014625  ... -0.102479 -0.019489  0.133210   
235  0.013416  0.057317 -0.087790  ...  0.000590  0.151953  0.115667   
236  0.019940 -0.036049 -0.070484  ...  0.012517  0.016850  0.054219   

           25        26        27        28        29        30        31  
0    0.043979 -0.034690  0.022817 -0.040245 -0.053900  0.009172  0.005099  
1    0.001297 -0.000227 -0.029726 -0.029355  0.030377 -0.088298 -0.016502  
2    0.172628 -0.034391 -0.033215  0.066284  0.004242  0.008450  0.063859  
3   -0.106033  0.016574 -0.042558  0.054139 -0.156296  0.043210 -0.015071  
4   -0.006428  0.027332  0.110127 -0.085280  0.111498 -0.014845 -0.047135  
..        ...       ...       ...       ...       ...       ...       ...  
232 -0.026866  0.033683 -0.003449  0.045210 -0.031737 -0.025112  0.094655  
233  0.072452 -0.120473  0.026516  0.012172 -0.079257 -0.053289 -0.018145  
234 -0.116215 -0.038889  0.151991 -0.147943  0.013299 -0.074997 -0.026430  
235  0.056416  0.038972  0.158752  0.062951  0.029513  0.047907  0.048659  
236  0.020620 -0.032010 -0.041517  0.033516 -0.024260  0.015738  0.046038  

[237 rows x 34 columns]

In [61]:
df = pd.read_csv("embeddings_df.csv")
df

Label         0         1         2         3         4         5  \
0      2.0  0.072486  0.000248 -0.004115 -0.127074 -0.022094  0.065082   
1      0.0  0.119010 -0.030075 -0.078117  0.012294 -0.050207 -0.080718   
2      0.0 -0.070066  0.032853  0.037138 -0.087919 -0.106282  0.100417   
3      1.0 -0.184983 -0.259079 -0.135025  0.120678  0.059934 -0.062732   
4      0.0  0.156783  0.042054 -0.097452 -0.094782 -0.209321  0.120856   
..     ...       ...       ...       ...       ...       ...       ...   
232    3.0 -0.267836 -0.258088  0.008073 -0.033932  0.112432 -0.090371   
233    3.0 -0.048973 -0.027855 -0.016548 -0.138835 -0.042492 -0.054023   
234    3.0 -0.225683 -0.042009  0.049713 -0.097044  0.032553 -0.016506   
235    3.0  0.148336  0.193006  0.016595  0.096854  0.186788  0.013495   
236    3.0  0.249120  0.169343 -0.095951 -0.023057  0.193757  0.019812   

            6         7         8  ...        22        23        24  \
0    0.003742  0.063882  0.053287  ...  0.001921 -0.112823  0.007213   
1    0.074633 -0.000086 -0.101405  ... -0.055586  0.036995 -0.027712   
2   -0.021176 -0.059002  0.087829  ...  0.058884  0.013660  0.061553   
3    0.084064  0.213234 -0.092404  ...  0.028968 -0.030234  0.002481   
4   -0.067509  0.153799  0.096455  ...  0.077904  0.022301 -0.027473   
..        ...       ...       ...  ...       ...       ...       ...   
232  0.087786  0.138120 -0.056336  ... -0.069588 -0.023723  0.001169   
233  0.069929 -0.018461  0.044041  ...  0.016757 -0.065773  0.108083   
234  0.000675 -0.014635  0.091858  ... -0.102810 -0.012759  0.122628   
235  0.057880 -0.087630 -0.074676  ... -0.009479  0.130207  0.108705   
236 -0.036081 -0.070357 -0.060360  ...  0.025133  0.023689  0.050695   

           25        26        27        28        29        30        31  
0    0.032006 -0.037990  0.019297 -0.024183 -0.027690  0.038694  0.063382  
1    0.000024 -0.008325 -0.024396 -0.016687 -0.005635 -0.094160  0.031379  
2    0.174045 -0.053489 -0.047574  0.031374 -0.036636 -0.010232 -0.096340  
3   -0.090266  0.032924 -0.052322 -0.013199 -0.092490  0.132573  0.055342  
4   -0.007752  0.037270  0.113074 -0.029237  0.058032 -0.101985  0.048814  
..        ...       ...       ...       ...       ...       ...       ...  
232 -0.028277  0.030329 -0.001013  0.029353 -0.118513  0.010326 -0.060841  
233  0.049610 -0.121704  0.014680  0.011982 -0.087532  0.022833  0.066126  
234 -0.116673 -0.051462  0.159170 -0.162949 -0.001091 -0.115758 -0.008652  
235  0.062347  0.054146  0.148231  0.093170  0.090770  0.061481 -0.042293  
236  0.026709 -0.022973 -0.040676 -0.013719 -0.003048  0.026220 -0.069927  

[237 rows x 33 columns]

In [62]:
df.dropna(inplace=True)

In [63]:
X = df.drop('Label', axis=1)
y = df['Label']

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [97]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [82]:
def train_model(X_train, X_test, y_train, y_test, algo):
    model = algo
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    #print("Recall:", recall_score(y_test, y_pred))
    #print("Precision:", precision_score(y_test, y_pred))

In [98]:
train_model(X_train, X_test, y_train, y_test, LogisticRegression())

Accuracy: 0.7288135593220338
[[12  4  6]
 [ 1 17  2]
 [ 1  2 14]]


In [99]:
train_model(X_train, X_test, y_train, y_test, SVC(kernel='linear'))

Accuracy: 0.7288135593220338
[[13  2  7]
 [ 2 16  2]
 [ 2  1 14]]


In [100]:
train_model(X_train, X_test, y_train, y_test, SVC(kernel='rbf'))

Accuracy: 0.7796610169491526
[[16  1  5]
 [ 1 17  2]
 [ 4  0 13]]


In [101]:
train_model(X_train, X_test, y_train, y_test, DecisionTreeClassifier())

Accuracy: 0.576271186440678
[[12  2  6  2]
 [ 2 13  5  0]
 [ 4  4  9  0]
 [ 0  0  0  0]]


In [102]:
train_model(X_train, X_test, y_train, y_test, RandomForestClassifier())

Accuracy: 0.6779661016949152
[[13  4  5]
 [ 1 17  2]
 [ 2  5 10]]


In [103]:
train_model(X_train, X_test, y_train, y_test, xgb.XGBClassifier())

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[18:38:54] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy: 0.6610169491525424
[[13  4  5  0]
 [ 1 17  2  0]
 [ 3  4  9  1]
 [ 0  0  0  0]]
